name: Deploy to WordPress.org

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: '1.0.0'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion
      - uses: actions/checkout@v2
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: export-order-items-for-woocommerce
          VERSION: ${{ github.event.inputs.version }}
