name: 'WordPress Plugin Check'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build plugin
        run: |
          mkdir -p ${{ runner.temp }}/export-order-items-for-woocommerce
          cp -r ./* ${{ runner.temp }}/export-order-items-for-woocommerce

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: ${{ runner.temp }}/export-order-items-for-woocommerce